import { UserPlus, Link2 } from "lucide-react";
import { assignAnalystClientAction, createAnalystAction } from "@/app/actions";
import { getAnalysts, getClients } from "@/lib/queries";
import { query } from "@/lib/db";
import { requireUser } from "@/lib/auth";

export default async function AnalystsPage(){
  await requireUser(["ADMIN"]);
  const [analysts,clients,links]=await Promise.all([getAnalysts(),getClients(),query<{analyst_name:string;client_name:string;is_primary:boolean}>(`SELECT u.name analyst_name,c.display_name client_name,ac.is_primary FROM analyst_clients ac JOIN users u ON u.id=ac.analyst_id JOIN clients c ON c.id=ac.client_id ORDER BY u.name,c.display_name`)]);
  return <><div className="page-head"><div><h1>Analistas</h1><p>Gerencie usuários operacionais e a carteira de clientes.</p></div></div>
  <div className="grid-2"><section className="card form-card"><h2 className="section-title" style={{marginTop:0}}>Cadastrar analista</h2><form action={createAnalystAction}><div className="form-grid"><div className="field"><label>Nome</label><input className="input" name="name" required/></div><div className="field"><label>Cargo</label><input className="input" name="position" placeholder="Analista"/></div><div className="field"><label>E-mail</label><input className="input" name="email" type="email" required/></div><div className="field"><label>Login</label><input className="input" name="username" required/></div><div className="field full"><label>Senha inicial</label><input className="input" name="password" type="password" minLength={6} required/></div></div><button className="btn btn-primary" style={{marginTop:18}}><UserPlus size={16}/> Criar analista</button></form></section>
  <section className="card form-card"><h2 className="section-title" style={{marginTop:0}}>Associar analista ao cliente</h2><form action={assignAnalystClientAction}><div className="field"><label>Analista</label><select className="select" name="analyst_id" required><option value="">Selecione</option>{analysts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><div className="field" style={{marginTop:12}}><label>Cliente</label><select className="select" name="client_id" required><option value="">Selecione</option>{clients.map(c=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></div><label className="check" style={{width:"fit-content",marginTop:12}}><input type="checkbox" name="is_primary"/> Analista principal do cliente</label><button className="btn btn-primary" style={{marginTop:18}}><Link2 size={16}/> Associar</button></form></section></div>
  <section className="card table-card"><div className="table-wrap"><table><thead><tr><th>Analista</th><th>Cliente</th><th>Principal</th></tr></thead><tbody>{links.rows.map((l,idx)=><tr key={`${l.analyst_name}-${l.client_name}-${idx}`}><td><strong>{l.analyst_name}</strong></td><td>{l.client_name}</td><td>{l.is_primary?<span className="badge RESOLVIDO">Sim</span>:"Não"}</td></tr>)}</tbody></table></div>{!links.rows.length&&<div className="empty"><strong>Sem associações</strong>Conecte analistas às carteiras que acompanham.</div>}</section></>;
}
